version: '3.1'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-test
    volumes:
      - './docker/mysql:/var/lib/mysql'

  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'
    networks:
      - app-test
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - app-test
    depends_on:
      - php

  redis:
    image: redis:latest
    networks:
      - app-test

  kafka:
    image: bitnami/kafka:latest
    networks:
      - app-test
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost

  zookeeper:
    image: zookeeper:latest
    networks:
      - app-test
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

networks:
  app-test:
    driver: bridge

